data_type: keyphrase

train_src: data/keyphrase/kp20k/kp20k_train_small.meng17.lower.src
train_tgt: data/keyphrase/kp20k/kp20k_train_small.meng17.lower.tgt
valid_src: data/keyphrase/kp20k/kp20k_valid.meng17.lower.src
valid_tgt: data/keyphrase/kp20k/kp20k_valid.meng17.lower.tgt

save_data: data/keyphrase/kp20k/kp20k.small.meng17
shard_size: 100000
dynamic_dict: 'true'
share_vocab: 'true'

src_seq_length_trunc: 300
tgt_seq_length_trunc: 8
lower: 'true'
filter_valid: 'false'

report_every: 1000
log_file: data/keyphrase/kp20k/preprocess.small.log
