data_type: keyphrase

train_src: data/keyphrase/magkp/magkp_train.one2many.src
train_tgt: data/keyphrase/magkp/magkp_train.one2many.tgt
valid_src: data/keyphrase/magkp/kp20k_valid.one2many.src
valid_tgt: data/keyphrase/magkp/kp20k_valid.one2many.tgt

save_data: data/keyphrase/magkp/magkp_train
shard_size: 100000
dynamic_dict: 'true'
share_vocab: 'true'

src_seq_length_trunc: 300
tgt_seq_length_trunc: 8
lower: 'true'
filter_valid: 'false'

report_every: 1000
log_file: data/keyphrase/magkp/preprocess.log
