model_type: keyphrase
tgt_type: random

#data: data/keyphrase/meng17/stackexchange
#data: data/keyphrase/meng17/kp20k
data: data/keyphrase/meng17/kp20k_small
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 3435
train_steps: 200000
valid_steps: 20000
report_every: 10

encoder_type: brnn
rnn_type: GRU
word_vec_size: 100
rnn_size: 150
layers: 1

optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1
max_grad_norm: 2

batch_size: 8
valid_batch_size: 128
dropout: 0.0

global_attention: mlp

tensorboard: 'true'
log_file_level: DEBUG

copy_attn: 'true'
reuse_copy_attn: 'true'
coverage_attn: 'true'
position_encoding: 'true'

context_gate: 'both'
input_feed: 1
copy_loss_by_seqlength: 'false'
share_embeddings: 'true'
bridge: 'true'

orth_reg: 'false'
lambda_orth_reg: 0.1
sem_cov: 'false'
lambda_sem_cov: 0.0

tgt_enc: 'none'
detach_tgt_enc: 'false'

exp: kp20k-one2seq-birnn-GRU150-EMB100-ATTNmlp-Dropout00
save_model: models/keyphrase/meng17-one2seq/kp20k.one2seq.birnn.Dropout00
log_file: output/keyphrase/meng17-one2seq/kp20k.one2seq.birnn.Dropout00.log
tensorboard_log_dir: runs/keyphrase/meng17-one2seq/kp20k.one2seq.birnn.Dropout00/

world_size: 1
gpu_ranks: []
#- 0
#- 1
master_port: 5000