model_type: keyphrase

data: data/keyphrase/kp20k/kp20k.one2one
save_model: models/keyphrase/kp20k/kp20k.one2one
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435
train_steps: 100000
valid_steps: 10000
report_every: 100

encoder_type: brnn
rnn_type: GRU
word_vec_size: 128
rnn_size: 512
layers: 1

optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1
max_grad_norm: 2

batch_size: 512
valid_batch_size: 16
dropout: 0.0

copy_attn: 'true'
global_attention: mlp
reuse_copy_attn: 'true'
copy_loss_by_seqlength: 'true'
bridge: 'true'

log_file: runs/keyphrase/kp20k/
log_file_level: DEBUG
exp: rnn-keyphrase-one2one-bi-GRU512-EMB128-ATTNmlp
tensorboard: 'true'
tensorboard_log_dir: runs/keyphrase/kp20k/

world_size: 2
gpu_ranks:
- 0
- 1
