data_type: keyphrase
train_src: data/keyphrase/kp20k/kp20k_training.json
train_tgt: data/keyphrase/kp20k/kp20k_training.json
valid_src: data/keyphrase/kp20k/kp20k_validation.json
valid_tgt: data/keyphrase/kp20k/kp20k_validation.json

save_data: data/keyphrase/kp20k/kp20k
shard_size: 50000

dynamic_dict: 'true'
share_vocab: 'true'

src_seq_length_trunc: 300
tgt_seq_length_trunc: 8
lower: 'true'
filter_valid: 'false'

report_every: 1000
log_file: data/keyphrase/kp20k/preprocess.log