data_type: text
train_src: data/summarization/cnndm/train.txt.src
train_tgt: data/summarization/cnndm/train.txt.tgt.tagged
valid_src: data/summarization/cnndm/val.txt.src
valid_tgt: data/summarization/cnndm/val.txt.tgt.tagged

save_data: data/summarization/cnndm/cnndm
dynamic_dict: 'true'
share_vocab: 'true'

src_seq_length_trunc: 300
tgt_seq_length_trunc: 8
lower: 'true'
filter_valid: 'false'

report_every: 1000
log_file: data/summarization/cnndm/preprocess.log